name: FactionsPlus
main: markehme.factionsplus.FactionsPlus
authors: ['MarkehMe', 'unv_annihilator', 'andrew2060', 'basicsensei']
website: http://markeh.me
version: 0.6.5
depend: [ Factions, Vault ]
soft-depend: [ DisguiseCraft, MobDisguise, LWC, WorldGuard, WorldEdit, Essentials, Multiverse-Portals, Lockette, ChestShop ]
dev-url: http://dev.bukkit.org/bukkit-plugins/factionsplus/
permissions:
  factionsplus.kit.jails:
    default: false
    description: all permissions about jails
    children:
      factionsplus.setjail: true
      factionsplus.jailunjail: true
      factionsplus.unsetjail: true
  factionsplus.kit.warps:
    default: false
    description: all permissions about warps
    children:
      factionsplus.createwarp: true
      factionsplus.warp: true
      factionsplus.deletewarp: true
      factionsplus.listwarps: true
  factionsplus.factionchatcommand:
    default: true
    description: if not given, disallows the use of /f fc 
  factionsplus.factionglobalchatcommand:
    default: true
    description: if not given, disallows the use of /f gc
  factionsplus.createwarp:
    default: true
    description: if not given, disallows the use of /f createwarp
  factionsplus.warp:
    default: true
    description: if not given, disallows the use of /f warp to teleport to predefined warps
  factionsplus.deletewarp:
    default: true
    description: if not given, disallows the use of /f deletewarp
  factionsplus.listwarps:
    default: true
    description: if not given, disallows the use of /f listwarps
  factionsplus.announce:
    default: true
    description: if not given, disallows the use of /f announce
  factionsplus.banunban:
    default: false
    description: if not given and furtherRestrictBanUnBanToThoseThatHavePermission is true, disallows the use of /f ban /f unban commands
  factionsplus.clearlwclocks:
    default: false
    description: if not given, disallows the use of /f clearlocks  which clears LWC locks in the current chunk
  factionsplus.otherfactionshome:
    default: false
    description: if not given, disallows the use of /f factionhome to teleport to other factions' home
  factionsplus.setjail:
    default: true
    description: if not given, disallows the use of /f setjail
  factionsplus.jailunjail:
    default: false
    description: if not given and furtherRestrictJailUnjailToThoseThatHavePermission is true, disallows the use of /f jail /f unjail commands
  factionsplus.unsetjail:
    default: true
    description: if not given, disallows the use of /f unsetjail to remove the jail location
  factionsplus.moneytop:
    default: true
    description: if not given, disallows the use of /f money top  which shows a list of richest factions
#  factions.reload:
#    default: false
#    description: if not given, disallows the use of /f reloadfp
  factionsplus.viewrules:
    default: true
    description: if not given, disallows the use of /f rules
  factionsplus.togglestate.use:
    default: false
    description: if not given, disallows /f togglestate which toggles own faction between peaceful and normal
  factionsplus.togglestate.others:
    default: false
    description: if not given, disallows /f togglestate from toggling peaceful for other factions
  factionsplus.dontPreventLWCLocking:
    default: false
    description: if not given, will allow you to LWC lock only in wilderness or your own faction; if given(or you're OP), you could in theory lock anywhere  
#  factionsplus.xyz:
#    default: false 
#    description: something
  factionsplus.*:
    description: all factionsplus permissions
    default: false
    children:
      factionsplus.kit.jails: true
      factionsplus.kit.warps: true
      factionsplus.factionchatcommand: true
      factionsplus.factionglobalchatcommand: true
      factionsplus.announce: true
      factionsplus.banunban: true
      factionsplus.clearlwclocks: true
      factionsplus.otherfactionshome: true
      factionsplus.moneytop: true
      factionsplus.viewrules: true
      factionsplus.togglestate.use: true
      factionsplus.togglestate.others: true
      factionsplus.dontPreventLWCLocking: true
#      factionsplus.xyz: true
